kind: Ingress
metadata:
  name: ddns-updater-ingress
  namespace: ddns-updater
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - host: ddns-updater.redacted.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ddns-updater-service
              port:
                number: 8000
